#!/bin/sh
set -e
set -u
# get all projects from file gsyn_all_projects
projects=$(cat "$HOME/gsyn/gsyn_all_projects")
echo following projects will be gsyn\'ed
echo '(change ~/gsyn/gsyn_all_projects, if you want different default ones)'
echo $projects

for proj in $projects; do
    echo
    eval echo "gsyn-synching project $proj"...
    echo "============================"
    echo 'expanded directory name:'
    proj_expanded=$(eval echo $proj)
    echo $proj_expanded
    echo
    gsyn $proj_expanded
done
