#!/bin/sh

cd "$(dirname "$0")" || exit 1    # Run from this directory

# symlink (not copy) into ~/bin: repo updates take effect without re-installing,
# and the scripts can find this repo via their real path (readlink -f)
mkdir -p "$HOME/bin"

ln -sf "$PWD/gsyn" "$HOME/bin/gsyn"
echo "gsyn installed for current user. i.e. symlink $HOME/bin/gsyn -> $PWD/gsyn"

ln -sf "$PWD/gsyn_all" "$HOME/bin/gsyn_all"
echo "gsyn_all installed for current user. i.e. symlink $HOME/bin/gsyn_all -> $PWD/gsyn_all"
